// Common DB types and models shared across the monorepo
import type {
  Workout,
  WorkoutTracking,
  WorkoutPlan,
  WeeklySchedule,
  ProgressTracking,
  AiChatMessages,
  AiSystemPrompt,
  NewWorkout,
  NewWorkoutTracking,
  NewWorkoutPlan,
  NewWeeklySchedule,
  NewOnboarding,
  NewAiChatMessages,
  NewAiSystemPrompt,
  Onboarding,
  User,
  PersonalTrainerInteraction,
  NewPersonalTrainerInteraction,
  NewProgressTracking,
} from "../../../apps/api/src/drizzle/src/db/queries";

export type {
  Workout,
  WorkoutTracking,
  WorkoutPlan,
  WeeklySchedule,
  ProgressTracking,
  AiChatMessages,
  AiSystemPrompt,
  NewWorkout,
  NewWorkoutTracking,
  NewWorkoutPlan,
  NewWeeklySchedule,
  NewOnboarding,
  NewAiChatMessages,
  NewAiSystemPrompt,
  Onboarding,
  User,
  PersonalTrainerInteraction,
  NewPersonalTrainerInteraction,
  NewProgressTracking,
}; 