CREATE TABLE "onboarding" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"step" text NOT NULL,
	"completed_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"name" text,
	"age" integer,
	"height" integer,
	"weight" integer,
	"gender" text,
	"fitness_level" text,
	"exercises" text[],
	"other_exercises" text[],
	"exercise_frequency" text,
	"session_length" text,
	"injuries" boolean,
	"injuries_details" text,
	"recent_surgery" boolean,
	"surgery_details" text,
	"chronic_conditions" text[],
	"other_health_conditions" text[],
	"pregnancy" text,
	"fitness_goals" text[],
	"goal_timeline" text,
	"specific_goals" text,
	"pilates_experience" boolean,
	"pilates_duration" text,
	"studio_frequency" text,
	"session_preference" text,
	"instructors" text[],
	"custom_instructor" text,
	"apparatus_preference" text[],
	"custom_apparatus" text,
	"motivation" text[],
	"other_motivation" text[],
	"progress_tracking" text[],
	"other_progress_tracking" text[]
);
--> statement-breakpoint
ALTER TABLE "onboarding" ADD CONSTRAINT "onboarding_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;